### ISSUE TITLE
Extract sequences of specific genes from genbank

### ISSUE THREAD

**Issue by fgvieira** [RaphaelHebert/nsdpy#38]
I am looking for a tool that can, given a genbank query, return the nucleotide sequence of a particular gene.
I came across `nsdpy` and it seems it can do it for `CDS` but not for `gene`. Any idea when the `gene` option will be fully functional?

**Comment by RaphaelHebert** [comment]
@fgvieira the PR for the gene option (gene feature) has not been closed yet but the project of adding a gene option is dropped (for now at least) as the idea was to download the gene_feature file available on NCBI GUI  with the Entrez APIs and parse it to extract the gene sequences info in order to extract the genes from the fasta file. The problem is that the  gene_feature file (.gff3 format) is not available via the Entrez APIs. 

The option -g --gff will be added to download these files by calling directly NCBI GUI address but this is more of an "experimental" option as it does not align with the NCBI [usage guidelines and requirements](https://www.ncbi.nlm.nih.gov/books/NBK25497/#_chapter2_Usage_Guidelines_and_Requiremen_) . 
The parsing of these .gff3 files will be left to the user for now. The option is already available one develop and on some beta versions (on Pypi tests). 

Some more beta versions of NSDPY are to be published during the coming days and the stable version should be released soon as well. Let me know if this option can be interesting for you I can make a beta version just for it. 

Also if you have idea and recommendations about the implementation of the gene option or other options that can be useful do not hesitate to contact me. The repo is open to external contributions as well.

**Comment by fgvieira** [comment]
Any reason why you decide to download th `.gff3` file? I thought `nsdpy` was downloading the genbank (`.gb`) files, since those have both the annotations and the sequence.

Either way, I'd be willing to test any version that could support downloading gene sequences.

**Comment by RaphaelHebert** [comment]
It turned out that the .gb files are harder to parse and have some (quite a lot for big datasets) inconsistencies, i.e. some of them are poorly annotated. So for the CDS download for example the .gb files are only downloaded and parsed for the TaxIDs that are not found in the fasta files.

**Comment by fgvieira** [comment]
Ok, so I'll give it a try to #33 and keep an eye on future beta releases.
thanks.

**Comment by RaphaelHebert** [comment]
Hello, here is a test version with the --gff option (-g)for downloading the gff3 files (works with -y to avoid the prompt and -v for more info) and the --custom option (-x ) for the taxonomic classification, the .md doc is up to date on the develop branch .
For install just copy/paste:
`pip install -i https://test.pypi.org/simple/ nsdpy==0.3.29b0`

**Comment by fgvieira** [comment]
Thanks, it seems to download the GFF fine but the all sequences start at position `1`.
How can I now extract the sequences for each GFF `gene` entry?

**Comment by RaphaelHebert** [comment]
@fgvieira In order to extract the gene sequences from fasta files with the info gathered from the .gff3 files, following a process like this can work I think:

1. parse the .gff3 files to extract the lines with the type field equal to "gene"
2. extract the start and end positions of the sequence
3. check the strand (if the strand is - then process it to get the complementary strand + )
4. get the sequence ID 
5. process the sequences from the fasta files with the corresponding information

Documentation on the .gff3 format: [GFF3 File Format - Definition and supported options](http://www.ensembl.org/info/website/upload/gff3.html)

Some work was started on this MR: [feature/geneFeature ](https://github.com/RaphaelHebert/nsdpy/pull/26)

It might be completed in a future release but so far I am not sure it is a robust way to get the gene sequences as the download of the .gff3 files cannot be done with the APIs and thus does not align with the requirements for programmatic download from NCBI. 
Parsing the .gb files could be a way to go but the files are heavier to download and a lot of inconsistencies do not allow the script to retrieve all the wanted sequences as well as parsing those files make the script more complicated and error-prone.
If you have ideas for NSDPY functionalities and implementation they are welcome! 

Hope it helps

**Comment by fgvieira** [comment]
Cool, Il'll give it a try!
thanks,
