### ISSUE TITLE
Species found with simple query go missing when adding more broad search terms

### ISSUE THREAD

**Issue by armandoep3** [RaphaelHebert/nsdpy#8]
Hi, first I would like to thank you for this great tool!
I have been using this for the last 2 weeks trying to figure out how to get the most out of nsdpy. However, unless I am mistaken there is an odd behaviour that I don't quite understand. I am trying to get generate a "clean" reference database for 1600 plants for the ITS, rbcL and trnL. I do not expect to get sequences for all the species as not all have public sequences yet. Here is the detail of what I am doing:

This query
nsdpy -r "Embryophyta[ORGN] AND internal transcribed spacer[All fields] AND 50:10000[SLEN] NOT gbdiv est[PROP] NOT gbdiv gss[PROP] NOT gbdiv env[PROP] NOT unverified[All Fields]" -Ti -L species_1600.txt

Returns: 31891 Sequences and 2270 Taxids

Then, with this additional terms ITS1 and ITS2
nsdpy -r "Embryophyta[ORGN] AND (ITS1[All fields] OR ITS2[All fields] OR internal transcribed spacer[All fields]) AND 50:10000[SLEN] NOT gbdiv est[PROP] NOT gbdiv gss[PROP] NOT gbdiv env[PROP] NOT unverified[All Fields]" -Ti -L species_1600.txt

Returns: 32876 Sequences and 2295 Taxids

Getting more sequences with the second is expected and for both queries there are some "missed" species (121 and 120 respectively). These are most often species that do not have public sequences yet.

However, the issue is that some of the species that were found with the first query are not found again with the second one!
For example, for Liriodendron tulipifera (taxid 3415) and Sambucus ebulus (taxid 28503) the first query returned 4 and 15 correct sequences respectively, but none with the second query.

I have reproduced this error for other barcodes, for example trying to get sequences for the rbcL for the same list of species.
1st query
nsdpy -r "Embryophyta[ORGN] AND ribulose-1,5-bisphosphate[All fields] AND 50:10000[SLEN] NOT gbdiv est[prop] NOT gbdiv gss[prop] NOT patent[All Fields] NOT gbdiv env[prop] NOT unverified[All Fields]" -Ti -L species_1600.txt

2nd query
nsdpy -r "Embryophyta[ORGN] AND (ribulose-1,5-bisphosphate[All fields] OR rbcl[gene]) AND 50:10000[SLEN] NOT gbdiv est[PROP] NOT gbdiv gss[PROP] NOT gbdiv env[PROP] NOT unverified[All Fields]" -Ti -L species_1600.txt

The difference between queries is not due to the species themselves. Indeed, both species previously mentioned have sequences for all rbcL queries.

Is this strange or am I doing something wrong ?

Best,

Armando

List of 1600 species
[species_1600.txt](https://github.com/RaphaelHebert/nsdpy/files/10091764/species_1600.txt)

**Comment by RaphaelHebert** [comment]
The query is getting too long, somehow splitting the query reduce the number of missing sequences.

**Comment by RaphaelHebert** [comment]
after I ran this queries, it looks like NSDPY is missing a taxa in each query it makes to NCBI. See on the following picture the stdout from NSDPY for the query `nsdpy -r "Embryophyta[ORGN] AND (ITS1[All fields] OR ITS2[All fields] OR internal transcribed spacer[All fields]) AND 50:10000[SLEN] NOT gbdiv est[PROP] NOT gbdiv gss[PROP] NOT gbdiv env[PROP] NOT unverified[All Fields]" -Ti -L species_1600.txt` and the part of the species_1600.txt concerned, we can see that blackstonia perfoliate is missing from the queries and this bug seems to repeat for every query. 
<img width="1440" alt="Screenshot 2023-09-27 at 10 11 34 PM" src="https://github.com/RaphaelHebert/nsdpy/assets/41419062/0eaf5a4b-30f2-494f-820f-0f0d7483ef03">
<img width="671" alt="listspecies" src="https://github.com/RaphaelHebert/nsdpy/assets/41419062/bb2efd39-9858-43d6-980f-2ae970c2d5f1">

I'll try to correct this in the week and adds UTs to the repo. Beta version will be available for testing on this thread.

**Comment by RaphaelHebert** [comment]
@armandoep3  the beta version for this bug fix is available:
`pip install -i https://test.pypi.org/simple/ nsdpy==0.3.32b0`
I am testing it on my side and it looks to go well so far.

with:
nsdpy -r "Embryophyta[ORGN] AND (ITS1[All fields] OR ITS2[All fields] OR internal transcribed spacer[All fields]) AND 50:10000[SLEN] NOT gbdiv est[PROP] NOT gbdiv gss[PROP] NOT gbdiv env[PROP] NOT unverified[All Fields]" -Ti -L species_1600.txt

Returns: 33978 Sequences and 2302 Taxids

**Comment by RaphaelHebert** [comment]
another bug was found:
search1:

~~~

nsdpy -r "Embryophyta[ORGN] AND (ITS1[All fields] OR ITS2[All fields] OR internal transcribed spacer[All fields]) AND 50:10000[SLEN] NOT gbdiv est[PROP] NOT gbdiv gss[PROP] NOT gbdiv env[PROP] NOT unverified[All Fields]" -Ti -L species_1600.txt

~~~

search2:

~~~
nsdpy -r "Embryophyta[ORGN] AND internal transcribed spacer[All fields] AND 50:10000[SLEN] NOT gbdiv est[PROP] NOT gbdiv gss[PROP] NOT gbdiv env[PROP] NOT unverified[All Fields]" -Ti -L species_1600.txt
~~~

Following taxids does not have sequences with the first query, but they do with the second (This is unexpected):

15304    3704   82736  119594  241224  434243   87752  360583   91248  106677  280011  702247    4079   53159 1080036   3415  47082   49614    3607   39414  397083  586403  267261   28503   57004   42036  764739  195145

**Comment by RaphaelHebert** [comment]
**Identified problem:**
- esearchquery calls **esearch** API with the following parameters:
`parameters = {
        **BASE_PARAMETERS,
        **({"api_key": str(api_key)} if api_key else {}),
        "db": "nucleotide",
        "idtype": "acc",
        "retmode": "json",
        "retmax": "0",
        **"usehistory": "y",**
        "term": query,
    }`
- **esearch** returns some values for the values _querykey_, _webenv_ and _count_
- _querykey_, _webenv_ and _count_ are used to call the **taxids** function that calls **ESUMMARY** with the following parameters: 
```
parameters = {
            **({"api_key": str(api_key)} if api_key else {}),
            "db": "taxonomy",
            "query_key": querykey,
            "WebEnv": webenv,
            "retstart": str(x * retmax),
            "retmax": str(retmax),
            "rettype": "uilist",
            "retmode": "text",
        }
```
- taxids proceeds the results to return a dict, the number of keys in the dict should be equal to the _count_ param from ESEARCH
- sometimes the returned dict misses some keys, check these two runs:
<img width="359" alt="Screenshot 2023-10-08 at 9 36 32 AM" src="https://github.com/RaphaelHebert/nsdpy/assets/41419062/2d2e84f6-93f8-48e7-afac-8e215ad59a9e">

<img width="340" alt="Screenshot 2023-10-07 at 9 57 44 PM" src="https://github.com/RaphaelHebert/nsdpy/assets/41419062/25354529-ed84-479b-bce8-438f2744205c">

On the first run see the underlined results. For the secon run no missing sequence and the total of entries betwin the 2 run (dict_ids.values) is equal to the missing sequences underlines on the first run.

**Proposed solution**
- check the implementation of the **taxids** function 
-  if the problem comes from the **ESUMMARY** check the returned dict from **taxids** and if the number of keys does not correspond to the _count_ parameter remake the call to retrieve the expected number of results.

**Comment by RaphaelHebert** [comment]
taxids function had few unconsitancies fixed in the following beta version:
pip install -i https://test.pypi.org/simple/ nsdpy==0.3.34b0

A new release will be issued soon with the changes.
